language: ruby
services:
- docker
before_install:
- docker-compose build
- docker-compose run web yarn --check-files
- docker-compose run web rake db:create
- docker-compose run web rake db:migrate

rvm:
- 2.6.6
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker tag blog_app_web:travis-final $DOCKER_USERNAME/blog_app_web:travis-final
- docker push $DOCKER_USERNAME/blog_app_web:travis-final